name = "the-watching-world"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "the-watching-world-db"
database_id = "88e2e779-ddd9-4cad-8cc5-631895bd5a4d" # Needs actual ID after `wrangler d1 create`
